# Generated by Django 2.0.3 on 2019-10-31 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItemCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraCheeseCost', models.FloatField()),
                ('onionToppingCost', models.FloatField()),
                ('grilledMushroomToppingCost', models.FloatField()),
                ('jalapenoToppingCost', models.FloatField()),
                ('blackOliveToppingCost', models.FloatField()),
                ('chickenToppingCost', models.FloatField()),
                ('bbqChickenToppingCost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isExtraCheese', models.BooleanField()),
                ('isOnionTopping', models.BooleanField()),
                ('isGrilledMushroomTopping', models.BooleanField()),
                ('isJalapenoTopping', models.BooleanField()),
                ('isBlackOliveTopping', models.BooleanField()),
                ('isChickenTopping', models.BooleanField()),
                ('isBbqChickenTopping', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallPizzaCost', models.FloatField()),
                ('mediiumPizzaCost', models.FloatField()),
                ('largePizzaCost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='pizzacost',
            name='pizzaName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myPizzaCost', to='orders.PizzaNames'),
        ),
        migrations.AddField(
            model_name='extraselected',
            name='pizzaName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myPizzaExtra', to='orders.PizzaNames'),
        ),
    ]
