# Generated by Django 2.0.3 on 2019-11-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaName', models.CharField(default=None, max_length=250)),
                ('pizzaSize', models.CharField(default=None, max_length=250)),
                ('pizzaCost', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedPizza', models.BooleanField(default=False)),
                ('pizzaName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedPizza', to='orders.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='ToppingsSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedToppings', models.BooleanField(default=False)),
                ('pizzaName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedPizzaToppings', to='orders.Pizza')),
            ],
        ),
        migrations.RemoveField(
            model_name='extraitemcost',
            name='toppingName',
        ),
        migrations.RemoveField(
            model_name='extraselected',
            name='pizzaName',
        ),
        migrations.RemoveField(
            model_name='extraselected',
            name='toppingsSelected',
        ),
        migrations.RemoveField(
            model_name='pizzacost',
            name='pizzaName',
        ),
        migrations.RemoveField(
            model_name='pizzacost',
            name='pizzaSize',
        ),
        migrations.RemoveField(
            model_name='pizzasize',
            name='pizzaName',
        ),
        migrations.RemoveField(
            model_name='pizzasizeselected',
            name='pizzaName',
        ),
        migrations.RemoveField(
            model_name='pizzasizeselected',
            name='selectedPizzaSize',
        ),
        migrations.AddField(
            model_name='toppings',
            name='toppingCost',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='toppingName',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.DeleteModel(
            name='ExtraItemCost',
        ),
        migrations.DeleteModel(
            name='ExtraSelected',
        ),
        migrations.DeleteModel(
            name='PizzaCost',
        ),
        migrations.DeleteModel(
            name='PizzaNames',
        ),
        migrations.DeleteModel(
            name='PizzaSize',
        ),
        migrations.DeleteModel(
            name='PizzaSizeSelected',
        ),
    ]
