# Generated by Django 2.0.3 on 2019-11-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191107_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaCost', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizzaselected',
            name='pizzaName',
        ),
        migrations.RemoveField(
            model_name='toppingsselected',
            name='pizzaName',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaSelected',
        ),
        migrations.DeleteModel(
            name='ToppingsSelected',
        ),
        migrations.AddField(
            model_name='pizzacost',
            name='pizzaName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaName'),
        ),
        migrations.AddField(
            model_name='pizzacost',
            name='pizzaSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaSize'),
        ),
    ]
